services:
  - type: web
    name: outfit-rec-api
    env: docker
    plan: starter
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: '1'
    ports:
      - 5000 